aap_organizations:
  - name: Tenant-1
    description: Organization for Tenant-1
    galaxy_credentials:
      - Ansible Galaxy
      - Private Hub Token
      - Private Hub Token Certified
      - Private Hub Token Validated

aap_user_accounts:
  - name: tenant1_admin
    username: tenant1_admin
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66376237633832363264666236646566303137323734653236636136323037306665353664613831
      3332666561306330626537333531366236393838313966320a633461623262323533373266303763
      36353763633061383439396363646162303031393066373066366662373266353865623363633933
      6563383535326162300a666138613432306438313236333531353331303835343065336462346438
      38363163333832353934626365323733616236353862373031636530386139336564383062643763
      6464306133626364663332383964366530306133323534616433
    first_name: Administrator
    last_name: Tenant1
    organization: Tenant-1

gateway_role_user_assignments:
  - role_definition: Organization Admin
    user: tenant1_admin
    # object_id: 2
    object_ids:
      - Tenant-1

# Skip this for now, we work with local users
#
# gateway_authenticator_maps:
#   - name: Tenant1-Organization-Administrators
#     authenticator: LDAP-Authenticator
#     revoke: true
#     map_type: organization
#     role: Organization Admin
#     triggers:
#       groups:
#         has_or:
#           - tenant1-org-admin

controller_credentials:
  - credential_type: Source Control
    name: 01 Tenant-1 Github Token
    description: Token for accessing Github
    inputs:
      username: github
      password: password
    organization: Tenant-1

controller_projects:
  - name: 01 Tenant-1 Organization Configuration
    scm_type: git
    scm_url: https://github.com/tosmi-ansible/tenant1-org-config.git
    scm_branch: main
    scm_clean: true
    credentials: 01 Tenant 1 Github Token
    description: Tenant1 Organization Configuration
    organization: Tenant-1
    wait: true
    update_project: true

controller_inventories:
  - name: 01 Tenant-1 Organization Configuration
    organization: Tenant-1

controller_templates:
  - name: 01 Tenant-1 Organization Configuration
    description: Apply Tenant 1 Organization configuration from GIT
    job_type: run
    inventory: 01 Tenant-1 Organization Configuration
    # credentials: admin@internal-RHVM-01
    project: 01 Tenant-1 Organization Configuration
    playbook: playbooks/org-config.yaml
    verbosity: 2
    extra_vars:
      target_hosts: infra-ansible-tower-01.example.com
